// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'548ce8340773fc79fe6cbef56f29dc4851b1c8c919516c3f3e14eb2ce9addf1d'>;
export type ExecutionHash =
  ExecutionHashBase<'b733fb8c32d83adf868dcc0e965f715dcda0728686440512a8c760a7a67cbed0'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Asset: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly mime_type: CodecTypes['pg/text@1']['output'];
      readonly original_name: CodecTypes['pg/text@1']['output'];
      readonly size_bytes: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly uploaded_by: CodecTypes['pg/uuid@1']['output'] | null;
    };
    readonly CustomView: {
      readonly configuration: CodecTypes['pg/jsonb@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_public: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly public_password: CodecTypes['pg/text@1']['output'] | null;
      readonly type: 'TABLE' | 'CHART';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly EventRegistration: {
      readonly accepts_image_usage: CodecTypes['pg/bool@1']['output'];
      readonly activity: 'HORA_DEL_CUENTO' | 'CIRCULO_DE_LECTURA' | 'TALLER';
      readonly activity_date: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly contact1_email: CodecTypes['pg/text@1']['output'] | null;
      readonly contact1_name: CodecTypes['pg/text@1']['output'] | null;
      readonly contact1_phone: CodecTypes['pg/text@1']['output'] | null;
      readonly contact1_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly contact2_email: CodecTypes['pg/text@1']['output'] | null;
      readonly contact2_name: CodecTypes['pg/text@1']['output'] | null;
      readonly contact2_phone: CodecTypes['pg/text@1']['output'] | null;
      readonly contact2_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly has_library_loan_record: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly needs_disability_support: CodecTypes['pg/bool@1']['output'];
      readonly participant_birthdate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly participant_education:
        'PREESCOLAR' | 'PRIMARIA' | 'SECUNDARIA' | 'BACHILLERATO' | 'LICENCIATURA' | 'POSGRADO';
      readonly participant_email: CodecTypes['pg/text@1']['output'] | null;
      readonly participant_gender: 'H' | 'M';
      readonly participant_name: CodecTypes['pg/text@1']['output'];
      readonly participant_neighborhood: CodecTypes['pg/text@1']['output'] | null;
      readonly participant_occupation:
        'HOGAR' | 'ESTUDIANTE' | 'TRABAJADOR' | 'JUBILADO' | 'DESOCUPADO';
      readonly participant_phone: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly FormConfig: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly form_identifier: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly public_password: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly User: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly password_hash: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'ANALYST';
      readonly totp_secret: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Asset: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly mime_type: CodecTypes['pg/text@1']['input'];
      readonly original_name: CodecTypes['pg/text@1']['input'];
      readonly size_bytes: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly uploaded_by: CodecTypes['pg/uuid@1']['input'] | null;
    };
    readonly CustomView: {
      readonly configuration: CodecTypes['pg/jsonb@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_public: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly public_password: CodecTypes['pg/text@1']['input'] | null;
      readonly type: 'TABLE' | 'CHART';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly EventRegistration: {
      readonly accepts_image_usage: CodecTypes['pg/bool@1']['input'];
      readonly activity: 'HORA_DEL_CUENTO' | 'CIRCULO_DE_LECTURA' | 'TALLER';
      readonly activity_date: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly contact1_email: CodecTypes['pg/text@1']['input'] | null;
      readonly contact1_name: CodecTypes['pg/text@1']['input'] | null;
      readonly contact1_phone: CodecTypes['pg/text@1']['input'] | null;
      readonly contact1_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly contact2_email: CodecTypes['pg/text@1']['input'] | null;
      readonly contact2_name: CodecTypes['pg/text@1']['input'] | null;
      readonly contact2_phone: CodecTypes['pg/text@1']['input'] | null;
      readonly contact2_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly has_library_loan_record: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly needs_disability_support: CodecTypes['pg/bool@1']['input'];
      readonly participant_birthdate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly participant_education:
        'PREESCOLAR' | 'PRIMARIA' | 'SECUNDARIA' | 'BACHILLERATO' | 'LICENCIATURA' | 'POSGRADO';
      readonly participant_email: CodecTypes['pg/text@1']['input'] | null;
      readonly participant_gender: 'H' | 'M';
      readonly participant_name: CodecTypes['pg/text@1']['input'];
      readonly participant_neighborhood: CodecTypes['pg/text@1']['input'] | null;
      readonly participant_occupation:
        'HOGAR' | 'ESTUDIANTE' | 'TRABAJADOR' | 'JUBILADO' | 'DESOCUPADO';
      readonly participant_phone: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly FormConfig: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly form_identifier: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly public_password: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly User: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly password_hash: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'ANALYST';
      readonly totp_secret: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Asset: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly mime_type: CodecTypes['pg/text@1']['output'];
      readonly original_name: CodecTypes['pg/text@1']['output'];
      readonly size_bytes: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly uploaded_by: CodecTypes['pg/uuid@1']['output'] | null;
    };
    readonly CustomView: {
      readonly configuration: CodecTypes['pg/jsonb@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_public: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly public_password: CodecTypes['pg/text@1']['output'] | null;
      readonly type: 'TABLE' | 'CHART';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly EventRegistration: {
      readonly accepts_image_usage: CodecTypes['pg/bool@1']['output'];
      readonly activity: 'HORA_DEL_CUENTO' | 'CIRCULO_DE_LECTURA' | 'TALLER';
      readonly activity_date: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly contact1_email: CodecTypes['pg/text@1']['output'] | null;
      readonly contact1_name: CodecTypes['pg/text@1']['output'] | null;
      readonly contact1_phone: CodecTypes['pg/text@1']['output'] | null;
      readonly contact1_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly contact2_email: CodecTypes['pg/text@1']['output'] | null;
      readonly contact2_name: CodecTypes['pg/text@1']['output'] | null;
      readonly contact2_phone: CodecTypes['pg/text@1']['output'] | null;
      readonly contact2_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly has_library_loan_record: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly needs_disability_support: CodecTypes['pg/bool@1']['output'];
      readonly participant_birthdate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly participant_education:
        'PREESCOLAR' | 'PRIMARIA' | 'SECUNDARIA' | 'BACHILLERATO' | 'LICENCIATURA' | 'POSGRADO';
      readonly participant_email: CodecTypes['pg/text@1']['output'] | null;
      readonly participant_gender: 'H' | 'M';
      readonly participant_name: CodecTypes['pg/text@1']['output'];
      readonly participant_neighborhood: CodecTypes['pg/text@1']['output'] | null;
      readonly participant_occupation:
        'HOGAR' | 'ESTUDIANTE' | 'TRABAJADOR' | 'JUBILADO' | 'DESOCUPADO';
      readonly participant_phone: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly FormConfig: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly form_identifier: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly public_password: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly User: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly password_hash: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'ANALYST';
      readonly totp_secret: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Asset: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly mime_type: CodecTypes['pg/text@1']['input'];
      readonly original_name: CodecTypes['pg/text@1']['input'];
      readonly size_bytes: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly uploaded_by: CodecTypes['pg/uuid@1']['input'] | null;
    };
    readonly CustomView: {
      readonly configuration: CodecTypes['pg/jsonb@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_public: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly public_password: CodecTypes['pg/text@1']['input'] | null;
      readonly type: 'TABLE' | 'CHART';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly EventRegistration: {
      readonly accepts_image_usage: CodecTypes['pg/bool@1']['input'];
      readonly activity: 'HORA_DEL_CUENTO' | 'CIRCULO_DE_LECTURA' | 'TALLER';
      readonly activity_date: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly contact1_email: CodecTypes['pg/text@1']['input'] | null;
      readonly contact1_name: CodecTypes['pg/text@1']['input'] | null;
      readonly contact1_phone: CodecTypes['pg/text@1']['input'] | null;
      readonly contact1_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly contact2_email: CodecTypes['pg/text@1']['input'] | null;
      readonly contact2_name: CodecTypes['pg/text@1']['input'] | null;
      readonly contact2_phone: CodecTypes['pg/text@1']['input'] | null;
      readonly contact2_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly has_library_loan_record: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly needs_disability_support: CodecTypes['pg/bool@1']['input'];
      readonly participant_birthdate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly participant_education:
        'PREESCOLAR' | 'PRIMARIA' | 'SECUNDARIA' | 'BACHILLERATO' | 'LICENCIATURA' | 'POSGRADO';
      readonly participant_email: CodecTypes['pg/text@1']['input'] | null;
      readonly participant_gender: 'H' | 'M';
      readonly participant_name: CodecTypes['pg/text@1']['input'];
      readonly participant_neighborhood: CodecTypes['pg/text@1']['input'] | null;
      readonly participant_occupation:
        'HOGAR' | 'ESTUDIANTE' | 'TRABAJADOR' | 'JUBILADO' | 'DESOCUPADO';
      readonly participant_phone: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly FormConfig: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly form_identifier: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly public_password: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly User: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly password_hash: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'ANALYST';
      readonly totp_secret: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Asset = {
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    mime_type: CodecTypes['pg/text@1']['output'];
    original_name: CodecTypes['pg/text@1']['output'];
    size_bytes: CodecTypes['pg/int4@1']['output'];
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    uploaded_by: CodecTypes['pg/uuid@1']['output'] | null;
    user: public_User | null;
    readonly [RelationKeys]?: 'user';
  };
  export type public_CustomView = {
    configuration: CodecTypes['pg/jsonb@1']['output'];
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    is_public: CodecTypes['pg/bool@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    public_password: CodecTypes['pg/text@1']['output'] | null;
    type: 'TABLE' | 'CHART';
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_EventRegistration = {
    accepts_image_usage: CodecTypes['pg/bool@1']['output'];
    activity: 'HORA_DEL_CUENTO' | 'CIRCULO_DE_LECTURA' | 'TALLER';
    activity_date: CodecTypes['pg/timestamp-temporal@1']['output'];
    contact1_email: CodecTypes['pg/text@1']['output'] | null;
    contact1_name: CodecTypes['pg/text@1']['output'] | null;
    contact1_phone: CodecTypes['pg/text@1']['output'] | null;
    contact1_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
    contact2_email: CodecTypes['pg/text@1']['output'] | null;
    contact2_name: CodecTypes['pg/text@1']['output'] | null;
    contact2_phone: CodecTypes['pg/text@1']['output'] | null;
    contact2_relation: 'PADRE' | 'MADRE' | 'TUTOR' | 'OTRO_FAMILIAR' | 'OTRO' | null;
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    has_library_loan_record: CodecTypes['pg/bool@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    needs_disability_support: CodecTypes['pg/bool@1']['output'];
    participant_birthdate: CodecTypes['pg/timestamp-temporal@1']['output'];
    participant_education:
      'PREESCOLAR' | 'PRIMARIA' | 'SECUNDARIA' | 'BACHILLERATO' | 'LICENCIATURA' | 'POSGRADO';
    participant_email: CodecTypes['pg/text@1']['output'] | null;
    participant_gender: 'H' | 'M';
    participant_name: CodecTypes['pg/text@1']['output'];
    participant_neighborhood: CodecTypes['pg/text@1']['output'] | null;
    participant_occupation: 'HOGAR' | 'ESTUDIANTE' | 'TRABAJADOR' | 'JUBILADO' | 'DESOCUPADO';
    participant_phone: CodecTypes['pg/text@1']['output'] | null;
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_FormConfig = {
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    form_identifier: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    is_active: CodecTypes['pg/bool@1']['output'];
    public_password: CodecTypes['pg/text@1']['output'] | null;
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_User = {
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    password_hash: CodecTypes['pg/text@1']['output'];
    role: 'ADMIN' | 'ANALYST';
    totp_secret: CodecTypes['pg/text@1']['output'] | null;
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    assets: public_Asset[];
    readonly [RelationKeys]?: 'assets';
  };
}

export declare const models: {
  public: {
    Asset: Models.public_Asset;
    CustomView: Models.public_CustomView;
    EventRegistration: Models.public_EventRegistration;
    FormConfig: Models.public_FormConfig;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Asset: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly mime_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly original_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly size_bytes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly uploaded_by: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Asset';
                    readonly columns: readonly ['uploaded_by'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly CustomView: {
              columns: {
                readonly configuration: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly is_public: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly public_password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly type: {
                  readonly nativeType: 'ViewType';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'ViewType' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly EventRegistration: {
              columns: {
                readonly accepts_image_usage: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly activity: {
                  readonly nativeType: 'ActivityType';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'ActivityType' };
                };
                readonly activity_date: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly contact1_email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly contact1_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly contact1_phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly contact1_relation: {
                  readonly nativeType: 'ContactRelation';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly typeName: 'ContactRelation' };
                };
                readonly contact2_email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly contact2_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly contact2_phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly contact2_relation: {
                  readonly nativeType: 'ContactRelation';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly typeName: 'ContactRelation' };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly has_library_loan_record: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly needs_disability_support: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly participant_birthdate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly participant_education: {
                  readonly nativeType: 'EducationLevel';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'EducationLevel' };
                };
                readonly participant_email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly participant_gender: {
                  readonly nativeType: 'Gender';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'Gender' };
                };
                readonly participant_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly participant_neighborhood: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly participant_occupation: {
                  readonly nativeType: 'Occupation';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'Occupation' };
                };
                readonly participant_phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly FormConfig: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly form_identifier: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly public_password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'FormConfig_form_identifier_key';
                  readonly columns: readonly ['form_identifier'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly User: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly password_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'Role';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'Role' };
                };
                readonly totp_secret: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'User_email_key';
                  readonly columns: readonly ['email'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ActivityType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['HORA_DEL_CUENTO', 'CIRCULO_DE_LECTURA', 'TALLER'];
            };
            readonly ContactRelation: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PADRE', 'MADRE', 'TUTOR', 'OTRO_FAMILIAR', 'OTRO'];
            };
            readonly EducationLevel: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PREESCOLAR',
                'PRIMARIA',
                'SECUNDARIA',
                'BACHILLERATO',
                'LICENCIATURA',
                'POSGRADO',
              ];
            };
            readonly Gender: { readonly kind: 'valueSet'; readonly values: readonly ['H', 'M'] };
            readonly Occupation: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'HOGAR',
                'ESTUDIANTE',
                'TRABAJADOR',
                'JUBILADO',
                'DESOCUPADO',
              ];
            };
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'ANALYST'];
            };
            readonly ViewType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['TABLE', 'CHART'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Asset: { readonly namespace: 'public' & NamespaceId; readonly model: 'Asset' };
    readonly CustomView: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CustomView';
    };
    readonly EventRegistration: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'EventRegistration';
    };
    readonly FormConfig: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FormConfig';
    };
    readonly User: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Asset: {
            readonly fields: {
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly mime_type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly original_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly size_bytes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly uploaded_by: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['uploaded_by'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Asset';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly id: { readonly column: 'id' };
                readonly mime_type: { readonly column: 'mime_type' };
                readonly original_name: { readonly column: 'original_name' };
                readonly size_bytes: { readonly column: 'size_bytes' };
                readonly updated_at: { readonly column: 'updated_at' };
                readonly uploaded_by: { readonly column: 'uploaded_by' };
              };
            };
          };
          readonly CustomView: {
            readonly fields: {
              readonly configuration: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly is_public: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly public_password: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'ViewType' };
                };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'CustomView';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly configuration: { readonly column: 'configuration' };
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly id: { readonly column: 'id' };
                readonly is_public: { readonly column: 'is_public' };
                readonly name: { readonly column: 'name' };
                readonly public_password: { readonly column: 'public_password' };
                readonly type: { readonly column: 'type' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly EventRegistration: {
            readonly fields: {
              readonly accepts_image_usage: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly activity: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'ActivityType' };
                };
              };
              readonly activity_date: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly contact1_email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contact1_name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contact1_phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contact1_relation: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'ContactRelation' };
                };
              };
              readonly contact2_email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contact2_name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contact2_phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contact2_relation: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'ContactRelation' };
                };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly has_library_loan_record: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly needs_disability_support: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly participant_birthdate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly participant_education: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'EducationLevel' };
                };
              };
              readonly participant_email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly participant_gender: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'Gender' };
                };
              };
              readonly participant_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly participant_neighborhood: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly participant_occupation: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'Occupation' };
                };
              };
              readonly participant_phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'EventRegistration';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly accepts_image_usage: { readonly column: 'accepts_image_usage' };
                readonly activity: { readonly column: 'activity' };
                readonly activity_date: { readonly column: 'activity_date' };
                readonly contact1_email: { readonly column: 'contact1_email' };
                readonly contact1_name: { readonly column: 'contact1_name' };
                readonly contact1_phone: { readonly column: 'contact1_phone' };
                readonly contact1_relation: { readonly column: 'contact1_relation' };
                readonly contact2_email: { readonly column: 'contact2_email' };
                readonly contact2_name: { readonly column: 'contact2_name' };
                readonly contact2_phone: { readonly column: 'contact2_phone' };
                readonly contact2_relation: { readonly column: 'contact2_relation' };
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly has_library_loan_record: { readonly column: 'has_library_loan_record' };
                readonly id: { readonly column: 'id' };
                readonly needs_disability_support: { readonly column: 'needs_disability_support' };
                readonly participant_birthdate: { readonly column: 'participant_birthdate' };
                readonly participant_education: { readonly column: 'participant_education' };
                readonly participant_email: { readonly column: 'participant_email' };
                readonly participant_gender: { readonly column: 'participant_gender' };
                readonly participant_name: { readonly column: 'participant_name' };
                readonly participant_neighborhood: { readonly column: 'participant_neighborhood' };
                readonly participant_occupation: { readonly column: 'participant_occupation' };
                readonly participant_phone: { readonly column: 'participant_phone' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly FormConfig: {
            readonly fields: {
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly form_identifier: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly is_active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly public_password: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'FormConfig';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly form_identifier: { readonly column: 'form_identifier' };
                readonly id: { readonly column: 'id' };
                readonly is_active: { readonly column: 'is_active' };
                readonly public_password: { readonly column: 'public_password' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly password_hash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'Role' };
                };
              };
              readonly totp_secret: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly assets: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Asset';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['uploaded_by'];
                };
              };
            };
            readonly storage: {
              readonly table: 'User';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly password_hash: { readonly column: 'password_hash' };
                readonly role: { readonly column: 'role' };
                readonly totp_secret: { readonly column: 'totp_secret' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Asset';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Asset';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'CustomView';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'CustomView';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'EventRegistration';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'EventRegistration';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'FormConfig';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'FormConfig';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'User';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'User';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
